// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2p7rFmGnc6x2Ax_0RYz-NiIQY0jjo5ps',
    appId: '1:457195115837:web:e1f83597025bf03ce1a154',
    messagingSenderId: '457195115837',
    projectId: 'kartbahn-99951',
    authDomain: 'kartbahn-99951.firebaseapp.com',
    storageBucket: 'kartbahn-99951.appspot.com',
    measurementId: 'G-5D8ZR1NQFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCurYv1XQqzG_Wnpr7zQ9FJy-RxAKiZSP4',
    appId: '1:457195115837:android:9f45dc290e2d0580e1a154',
    messagingSenderId: '457195115837',
    projectId: 'kartbahn-99951',
    storageBucket: 'kartbahn-99951.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcf1iCTHj0BkmpMiixPdbIxghbzqSfYVY',
    appId: '1:457195115837:ios:ef41bf29b75ea686e1a154',
    messagingSenderId: '457195115837',
    projectId: 'kartbahn-99951',
    storageBucket: 'kartbahn-99951.appspot.com',
    iosBundleId: 'com.example.kartbahnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcf1iCTHj0BkmpMiixPdbIxghbzqSfYVY',
    appId: '1:457195115837:ios:17a8ffd1246ff3bae1a154',
    messagingSenderId: '457195115837',
    projectId: 'kartbahn-99951',
    storageBucket: 'kartbahn-99951.appspot.com',
    iosBundleId: 'com.example.kartbahnApp.RunnerTests',
  );
}
